sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3  
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
script:
  - bundle exec rspec
